### PR TITLE
Data Preparation and Analysis of Nigeria Crime Dataset

### LINKED ISSUE #3: Exploratory Data Analysis - Data Visualization 📊
### **Project Overview**

An important component of EDA is Data Visualizations. We need to perform data visualization so as to better understand the data provided

### **What is Needed**
Contributors are required to perform an Indepth data visualization on the provided dataset. This will help to better understand the distribution of the data, detect outlier, identify patterns and explore relationships.

### **How to Contribute**
1. Get familiar with the notebook and documentations already provided in the [repository](https://github.com/mlsanigeria/nigeria-crime-trends).
2.  Implement various data visualizations on the dataset
3. Create a Pull Request: Submit a pull request to the repository with your code in your created folder and include any necessary documentation.

### **Getting Started**
Before you begin, ensure you have read the [Contribution Guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) so that your contribution can be effective.

Looking forward to your solutions! Happy Hacking! 🎉

### PR DESCRIPTION
**Pull request by AiratAroyewun**
I created a full preparation and analysis of the Nigeria Crime Dataset

### CODE REVIEW

**Review by Sammybams — APPROVED** [review]
Amazing work @AiratAroyewun. I like how you followed the sample provided month Africa scale. You added the whole dataset to your folder which I have removed. We do not need duplicates of that since it already exists in the `data` directory in the repo. I also deleted a `dataset` file which I believe you created in error.

Great work on the analysis @AiratAroyewun. Thank you very much for your contribution.

**Comment by Sammybams** [comment]
By the way @AiratAroyewun,  you didn't follow the correct naming convention of `experimentation_{GitHub_Username}`. You named it experiment then combined it with your first name. I have fixed that on my end already though.

**Comment by AiratAroyewun** [comment]
Oh my bad, I'm just familiarizing myself with contributing on GitHub. Thank you.

**Comment by Sammybams** [comment]
> Oh my bad, I'm just familiarizing myself with contributing on GitHub. Thank you.

You're doing great @AiratAroyewun. Weldone.

**Pull request merged**
