### PR TITLE
Model building and hyperparameter tuning

### PR DESCRIPTION
**Pull request by MariaMahmood18**
In the notebook, detailed modeling steps are performed with regression models like:

1.  Linear Regression 
2. Random Forest Regressor
3. SGD Regressor. 

Out of which Random Forest Regressor was the best performing model. Further hyperparameter tuning was performed using RandomizedSearchCV for the Random Forest Regressor. 

After detailed comparison the hyperparameter tuned model performed well. In the end a feature importance analysis is carried out.

### CODE REVIEW

**Review by Sammybams — CHANGES_REQUESTED** [review]
Thank you very much for your contribution @MariaMahmood18. You would need to make some changes before we can merge your PR. You dropped some very important columns like `actor1` and `month` for your modelling and we would request you to include these in your training. And also does the `SDGClassifier` work as a regression model or classification model? 

You also do not need to make duplicates of the csv files in your own folder as you can reference them from the data directory and from other locations. If you did your own unique cleaning, then you can include that. So kindly delete the original dataset in your new PR.

**Comment by MariaMahmood18** [comment]
Thanks for pointing that out, and apologies for my oversight. I'll update
the file.

**Comment by MariaMahmood18** [comment]
I have made the requested changes by restoring the actor1 and month columns, and replacing SGDClassifier with SGDRegressor, and removing the duplicate CSV files. 
Please let me know if anything else is needed!

**Review by Sammybams — APPROVED** [review]
Great work @MariaMahmood18. Thank you very much.

**Pull request merged**
