### PR TITLE
added required file

### PR DESCRIPTION
**Pull request by Somyyaa**
Issue #4 
Feature engineering has been performed along with label encoding to convert the data into numeric data to perform ML modeling.
Logistic regression, naive bayes, kNN, random forest, bagging and boosting ML models have been applied to the dataset where random forest gives the maximum accuracy.
F1 score and accuracies have been found.
image
image

### CODE REVIEW

**Review by Sammybams — COMMENTED** [review]
Thank you for your contribution @Somyyaa. But we cannot merge your PR because the modelling isn't totally right. The fatalities column is a continuous variable and hence is a regression problem. Please do follow the [contribution guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) by checking the starter notebook to see the basic guide on what the solution for the project should be around. Thank you.

**Review by Sammybams — CHANGES_REQUESTED** [review]
The requested changes have been indicated in the first comment.

**Comment by Somyyaa** [comment]
> Thank you for your contribution @Somyyaa. But we cannot merge your PR because the modelling isn't totally right. The fatalities column is a continuous variable and hence is a regression problem. Please do follow the [contribution guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) by checking the starter notebook to see the basic guide on what the solution for the project should be around. Thank you.

Okay, got it! Will try to make the necessary changes.

**Comment by Somyyaa** [comment]
> > Thank you for your contribution @Somyyaa. But we cannot merge your PR because the modelling isn't totally right. The fatalities column is a continuous variable and hence is a regression problem. Please do follow the [contribution guidelines](https://github.com/mlsanigeria/nigeria-crime-trends/blob/main/CONTRIBUTING.md) by checking the starter notebook to see the basic guide on what the solution for the project should be around. Thank you.
> 
> Okay, got it! Will try to make the necessary changes.

I have made the necessary changes as suggested by you and made the PR against issue #4 again. Please review. Thanks

**Pull request closed without merging**
