### PR TITLE
Data Cleaning and Preprocessing and EDA

### PR DESCRIPTION
**Pull request by Odeyiany2**
I added my notebook in my folder containing my data cleaning and preprocessing steps for issue #2.

### CODE REVIEW

**Review by Sammybams — CHANGES_REQUESTED** [review]
Hi @Odeyiany2, thank you very much for your contribution. However you analysis doesn't tell much story, there are no visuals/plots. We would be happy to merge your pull requests once you have much more details in your notebook.

**Comment by Odeyiany2** [comment]
Hii @Sammybams I have made updates to my notebook. Please confirm if you can see them. Thank you.

**Review by QuCoon-ML-AI — CHANGES_REQUESTED** [review]
Hi @Odeyiany2, thank you very much. But we can't still merge your contribution at this point. Some of your analyses are fine, but many are difficult to understand because of the colour coding used. And also there seems to be an excessive use of bar charts and multiples in one, so even making some much smaller than the other because there are on different scales (in terms of maximum and distribution).

We believe you can improve on this and we strongly recommend you go through this [notebook sample](https://github.com/Sammybams/HamoyeAI-Team-Theano-Capstone-Project/blob/master/experimentation/Full%20Analysis%20of%20Crime%20Dataset%20(1997%20to%202023%20March%2031st).ipynb) that does a full analysis on this same dataset but on an African level.

**Review by Sammybams — CHANGES_REQUESTED** [review]
Hi @Odeyiany2, thank you very much. But we can't still merge your contribution at this point. Some of your analyses are fine, but many are difficult to understand because of the colour coding used. And also there seems to be an excessive use of bar charts and multiples in one, so even making some much smaller than the other because there are on different scales (in terms of maximum and distribution).

We believe you can improve on this and we strongly recommend you go through this [notebook sample](https://github.com/Sammybams/HamoyeAI-Team-Theano-Capstone-Project/blob/master/experimentation/Full%20Analysis%20of%20Crime%20Dataset%20(1997%20to%202023%20March%2031st).ipynb) that does a full analysis on this same dataset but on an African level.

**Comment by Odeyiany2** [comment]
> Hi @Odeyiany2, thank you very much. But we can't still merge your contribution at this point. Some of your analyses are fine, but many are difficult to understand because of the colour coding used. And also there seems to be an excessive use of bar charts and multiples in one, so even making some much smaller than the other because there are on different scales (in terms of maximum and distribution).
> 
> We believe you can improve on this and we strongly recommend you go through this [notebook sample](https://github.com/Sammybams/HamoyeAI-Team-Theano-Capstone-Project/blob/master/experimentation/Full%20Analysis%20of%20Crime%20Dataset%20(1997%20to%202023%20March%2031st).ipynb) that does a full analysis on this same dataset but on an African level.

Okay I will do that. Thank you.

**Pull request closed without merging**
